client_id = "1"
shares_to_create = 3
shares_required = 2
#Â api_key =


[[servers]]
id = "1"
addr = "127.0.0.1:8080"

[[servers]]
id = "2"
addr = "127.0.0.1:8081"

[[servers]]
id = "3"
addr = "127.0.0.1:8082"




